### ISSUE TITLE
error when editable = False

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-Simpmotion#16]
Just noticed this tool is now erroring at the final "get your docs" page when the main PDF is set to be flat (editable = False), but it works fine with editable is set to True.

I could have sworn this was working before.  

Error:
"Call to pdftk failed for template /tmp/playgroundtemplate/4/SimpleMotion/simpmotion.pdf where arguments were pdftk /tmp/playgroundtemplate/4/SimpleMotion/simpmotion.pdf fill_form /tmp/datemp14588bto.xfdf output /tmp/datemp8mv2sb0n.pdf replacement_font /usr/share/fonts/truetype/msttcorefonts/Arial.ttf flatten: b’Error: Unexpected data in output section: \n replacement_font\nExiting.\nErrors encountered. No output created.\nDone. Input errors, so no output created.\n’"

@BryceStevenWilley do you have any thoughts?

**Comment by BryceStevenWilley** [comment]
That looks like it's something added in a [recent version of docassemble (1.4.79)](https://github.com/jhpyle/docassemble/blob/master/CHANGELOG.md#1479---2023-09-18), so I don't think we're doing anything wrong.

I'll try to recreate the issue and make an upstream fix, and if I don't understand what's happening, I'll see if Jonathan knows what's going on.

**Comment by BryceStevenWilley** [comment]
Found it; the recent changes in docassemble assume that [pdftk is version `3.3.0`](https://gitlab.com/pdftk-java/pdftk/-/blob/master/CHANGELOG.md?ref_type=heads#330-2021-08-16). However, that's only been the case for docker images made in the [last month](https://github.com/jhpyle/docassemble-os/commit/ffa0522808ed65af7b7a1f7ef9f87c6234e5558f), which isn't a long enough timeline to upgrade.

I've made an upstream patch, I'm testing to make sure it'll work right now. It should let us upgrade the docassemble version without having to upgrade the docker container

**Comment by BryceStevenWilley** [comment]
Jonathan beat me to it, but Docassemble 1.4.81 has the fix! I upgraded the dev server to 1.4.81, and it fixes the problem for me. Let me know if the issue goes away for you too @ekressmiller

**Comment by ekressmiller** [comment]
Thank you Bryce! Yes it's working for me again on the dev server.  

For future reference, this line from the 1.4.73 changelog is what should have clued me in we needed a docker update, correct?
"Upgraded pdftk and Pandoc (system upgrade required)."

I think I absorbed a bit too relaxed of an attitude about when a docker update was really required.

I will let Scott know we should do a docker upgrade when he has a chance.

**Comment by BryceStevenWilley** [comment]
Yep, that's the line. TBH, it's something if I had looked at it before this broke, I would have said the docker update would be nice, but not necessary. IMO you weren't being too relaxed, docassemble just breaks now and then.

**Comment by ekressmiller** [comment]
OK, thanks!
