### ISSUE TITLE
Review screen error when no plaintiff

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-Simpmotion#33]
Merged Bryce's review screen work and it's much closer!  

Still had an issue: I switched user's party affiliation several times.  All fine. 

With user set to plaintiff, I deleted the defendant on the review screen. Then I switched user back to defendant.  The review screen showed this for plaintiff:
![image](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/8d00c15e-c43b-4423-a35b-128d0a589ced)

And when I clicked "Continue interview" I got an error:  "IndexError: list index out of range"
[no-plaintiff-full-error-msg.txt](https://github.com/mplp/docassemble-Simpmotion/files/13866025/no-plaintiff-full-error-msg.txt)

**Comment by ekressmiller** [comment]
variables, if needed: [troubleshoot_vars.txt](https://github.com/mplp/docassemble-Simpmotion/files/13866047/troubleshoot_vars.txt)

**Comment by ekressmiller** [comment]
@BryceStevenWilley no pressure at all to get to this, I'm happy to take a stab and/or work with the Lemma Legal folks, but just in case you have time/interest, this is the error I'm still having with the review screen.

Thanks again for all your work on the review logic.

**Comment by BryceStevenWilley** [comment]
I didn't see this issue, sorry! I checked it out, and I think I have a fix. Making a PR now

**Comment by ekressmiller** [comment]
Thanks for your work on this Bryce! This seems to fix the original error, but now I get "AttributeError: there_are_any" when I initially answer that I am the plaintiff and there is **no** defendant, and then try to switch my party from plaintiff to defendant.

Will keep working on it.

[detailed-error.txt](https://github.com/mplp/docassemble-Simpmotion/files/13969280/detailed-error.txt)

**Comment by BryceStevenWilley** [comment]
Thanks! Sorry, that was sloppy on my part, I coded it to delete the `there_are_any` attribute even if there wasn't one. That should be fixed now, give it another shot and let me know if it's still erroring in that case!

**Comment by ekressmiller** [comment]
Awesome, thanks!
