### ISSUE TITLE
ID You Must Already Have a Court Case to Use This Tool: 
User feedback: something
(`existing_case`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-Simpmotion#37]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `You Must Already Have a Court Case to Use This Tool`
Details | new prod server test test test test test
Variable being sought | `existing_case`
Package version | `1.5.2`
Filename | `docassemble.Simpmotion:data/questions/simpmotion.yml`

**Comment by ekressmiller** [comment]
test
