### ISSUE TITLE
ID Is this a criminal case: 
User feedback: something
(`criminal_case`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-Simpmotion#38]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Is this a criminal case`
Details | tes test test new server share answers checked
Variable being sought | `criminal_case`
Package version | `1.5.2`
Filename | `docassemble.Simpmotion:data/questions/simpmotion.yml`

**Comment by ekressmiller** [comment]
test
