### ISSUE TITLE
ID Is this a probate case: 
User feedback: something
(`probate_case`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-Simpmotion#39]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Is this a probate case`
Details | TEST TEST TEST da-prod, "share my answers" checked
Variable being sought | `probate_case`
Package version | `1.4`
Filename | `docassemble.Simpmotion:data/questions/simpmotion.yml`

**Comment by ekressmiller** [comment]
test
