### ISSUE TITLE
ID download simpmotion: 
User feedback: language
(`simpmotion_download`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-Simpmotion#4]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `download simpmotion`
Details | TEST  TEST TEST
Variable being sought | `simpmotion_download`
Package version | `playground`
Maturity target | Level 1.5 - it works as-is, but this is a significant plain language issue
Filename | `docassemble.playground4SimpleMotion:simpmotion.yml`

**Comment by ekressmiller** [comment]
(This was just a test.)
