### ISSUE TITLE
ID MLH intro time: 
User feedback: something
(`MLH_intro_time`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-Simpmotion#43]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `MLH intro time`
Details | test test
Variable being sought | `MLH_intro_time`
Package version | `1.5.2`
Filename | `docassemble.Simpmotion:data/questions/simpmotion.yml`

**Comment by ekressmiller** [comment]
test issue
