### ISSUE TITLE
ID You Must Already Have a Court Case to Use This Tool: 
User feedback: bug
(`existing_case`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-Simpmotion#5]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `You Must Already Have a Court Case to Use This Tool`
Details | prod server TEST TEST TEST TEST

This form is my favorite form in the world but I think you should also spell color with a u.
Variable being sought | `existing_case`
Package version | `playground`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Filename | `docassemble.playground3:simpmotion.yml`

**Comment by ekressmiller** [comment]
This was just a test.
